[tools]
selene = { source = "Kampfkarren/selene", version = "0.21.0" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.14.2" }
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
wally = { source = "upliftgames/wally", version = "0.3.1" }
